---
- name: "Install Fluentd prerequisites."
  apt:
    name: "{{ fluentd_prerequisites }}"
    state: present

- name: "Add Fluentd key."
  apt_key:
    url: "{{ fluentd_apt_key_url }}"
    state: present

- name: "Add Fluentd repository."
  apt_repository:
    repo: "deb {{ fluentd_apt_repos_url }} contrib"
    update_cache: True
    filename: fluentd
    state: present

- name: "Get installed Fluentd version."
  command: dpkg-query --showformat='${Version}' --show {{ fluentd_pkg_name }}
  register: fluentd_pkg_installed_version
  failed_when: False
  changed_when: False
  check_mode: no

- name: "Unhold Fluentd version."
  dpkg_selections:
    name: "{{ fluentd_pkg_name }}"
    selection: install
  when: not fluentd_pkg_version_hold or (fluentd_pkg_installed_version.stdout and fluentd_pkg_installed_version.stdout != fluentd_pkg_version)

- name: "Install Fluentd."
  apt:
    name: "{{ fluentd_pkg_name }}{% if fluentd_pkg_version is defined and fluentd_pkg_version != '' %}={{ fluentd_pkg_version }}{% endif %}"
    cache_valid_time: 3600
    state: present

- name: "Hold Fluentd version."
  dpkg_selections:
    name: "{{ fluentd_pkg_name }}"
    selection: "hold"
  when: fluentd_pkg_version_hold

- name: "Install Fluentd plugins."
  gem:
    name: "{{ item.name }}"
    executable: "{{ fluentd_gem_exec_path }}"
    user_install: False
    version: "{{ item.version | default(omit) }}"
    state: present
  loop: "{{ fluentd_plugins }}"
  notify: "Restart Fluentd."

- name: "Enable Fluentd service."
  service:
    name: "{{ fluentd_svc_name }}"
    enabled: True

- name: "Create Fluentd configuration directory."
  file:
    path: "{{ fluentd_conf_dir }}"
    state: directory
    mode: 0750
  when: fluentd_conf_dir is defined

- name: "Create main Fluentd configuration."
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    mode: 0640
    owner: td-agent
    group: td-agent
  notify: "Restart Fluentd."
